// api/workorders/send.js
import path from "path";
import fs from "fs";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import czsClient from "../../src/lib/czsClient.js";

const BREVO_API_KEY = process.env.BREVO_API_KEY;

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { workOrderId, emailToSend } = req.body;
    if (!workOrderId || !emailToSend) {
      return res
        .status(400)
        .json({ error: "Missing parameters: workOrderId, emailToSend" });
    }

    console.log("📩 Received payload:", { workOrderId, emailToSend });

    // 1️⃣ Fetch Work Order
    const { data: wo, error } = await czsClient
      .from("work_orders")
      .select("*")
      .eq("id", workOrderId)
      .single();

    if (error || !wo) throw new Error("Work order not found");

    // 2️⃣ Build PDF (unicode safe)
    const pdfDoc = await PDFDocument.create();
    pdfDoc.registerFontkit(fontkit);

    // ✅ Unicode TTF font (npr. DejaVuSans)
    const fontPath = path.resolve("./public/fonts/DejaVuSans.ttf");
    const fontBytes = fs.readFileSync(fontPath);
    const customFont = await pdfDoc.embedFont(fontBytes);

    const page = pdfDoc.addPage([595.28, 841.89]); // A4
    const { width } = page.getSize();
    let y = 800;

    const drawText = (label, val, offset = 180) => {
      page.drawText(label, { x: 40, y, size: 12, font: customFont, color: rgb(0, 0, 0) });
      page.drawText(String(val || "-"), {
        x: offset,
        y,
        size: 12,
        font: customFont,
        color: rgb(0, 0, 0),
      });
      y -= 18;
    };

    page.drawText("RADNI NALOG / WORK ORDER", {
      x: 40,
      y: 820,
      size: 16,
      font: customFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    drawText("Order no:", wo.order_no);
    drawText("Customer:", wo.customer_name);
    drawText("Email:", emailToSend);
    drawText("Purity:", wo.purity);
    drawText("Color:", wo.color);
    drawText("Quantity:", wo.quantity);
    drawText("Status:", wo.status);
    y -= 20;
    drawText("Created:", new Date().toLocaleString());
    y -= 30;

    page.drawText("Generated by ORCA System", {
      x: 40,
      y: 60,
      size: 10,
      font: customFont,
      color: rgb(0.4, 0.4, 0.4),
    });

    const pdfBytes = await pdfDoc.save();
    const pdfBase64 = Buffer.from(pdfBytes).toString("base64");

    // 3️⃣ Send via Brevo
    const payload = {
      sender: { name: "ORCA Production", email: "noreply@orca.hr" },
      to: [{ email: emailToSend }],
      subject: `Radni nalog ${wo.order_no}`,
      htmlContent: `<p>Poštovani,</p><p>U privitku se nalazi radni nalog <b>${wo.order_no}</b>.</p><p>Srdačan pozdrav,<br/>ORCA Team</p>`,
      attachment: [
        {
          name: `${wo.order_no || "workorder"}.pdf`,
          content: pdfBase64,
        },
      ],
    };

    const brevoRes = await fetch("https://api.brevo.com/v3/smtp/email", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "api-key": BREVO_API_KEY,
      },
      body: JSON.stringify(payload),
    });

    if (!brevoRes.ok) {
      const msg = await brevoRes.text();
      throw new Error(`Brevo send failed: ${msg}`);
    }

    // 4️⃣ Log update
    const logEntry = {
      time: new Date().toISOString(),
      recipient: emailToSend,
      order_no: wo.order_no,
    };
    await czsClient
      .from("work_orders")
      .update({
        email_log: [...(wo.email_log || []), logEntry],
      })
      .eq("id", wo.id);

    return res.status(200).json({
      ok: true,
      mailed: true,
      pdfBase64,
      order_no: wo.order_no,
    });
  } catch (err) {
    console.error("❌ send.js error:", err);
    return res
      .status(500)
      .json({ error: err.message || "Server error", mailed: false });
  }
}
