const fs = require("fs");
const path = require("path");
const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");
const fontkit = require("@pdf-lib/fontkit");
const { createClient } = require("@supabase/supabase-js");

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const BREVO_API_KEY = process.env.BREVO_API_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const FONT_PATH = path.join(process.cwd(), "public", "fonts", "NotoSans-Regular.ttf");

// 🔧 Helpers
const safe = (v) => (v && v !== "null" && v !== "undefined" ? String(v) : "-");
const formatDate = (v) => (v ? new Date(v).toLocaleString("hr-HR") : "-");

// 🧾 PDF builder
async function buildPdf(order, company) {
  const pdfDoc = await PDFDocument.create();
  pdfDoc.registerFontkit(fontkit);

  let fontBytes;
  try {
    fontBytes = fs.readFileSync(FONT_PATH);
  } catch {}
  const font = fontBytes
    ? await pdfDoc.embedFont(fontBytes)
    : await pdfDoc.embedFont(StandardFonts.Helvetica);

  const page = pdfDoc.addPage([595, 842]);
  const { width, height } = page.getSize();
  let y = height - 60;

  const draw = (text, x, dy = 0, size = 11) => {
    page.drawText(text || "-", { x, y: dy || y, size, font, color: rgb(0, 0, 0) });
  };

  // 🏢 Header
  const cname = safe(company?.legal_name || "Zlatarna Krizek doo");
  const caddr = `${safe(company?.address_line)}, ${safe(company?.city)}, ${safe(company?.country)}`;
  draw(cname, 40, y, 16);
  draw(caddr, 40, y - 18, 10);
  draw(`${safe(company?.email)} | ${safe(company?.phone)} | OIB: ${safe(company?.tax_id)}`, 40, y - 32, 10);

  y -= 70;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 1, color: rgb(0, 0, 0) });
  y -= 25;
  draw(`RADNI NALOG ${safe(order.order_no)}`, 40, y, 18);
  y -= 24;
  draw(`Datum narudžbe: ${formatDate(order.order_date)}`, 40, y);
  draw(`Rok izrade: ${formatDate(order.due_date)}`, 300, y);

  const section = (title) => {
    y -= 22;
    page.drawLine({
      start: { x: 40, y },
      end: { x: width - 40, y },
      thickness: 0.5,
      color: rgb(0.6, 0.6, 0.6),
    });
    y -= 20;
    draw(title, 40, y, 13);
    y -= 18;
  };

  // 👤 Kupac
  section("KUPAC");
  draw(`Ime: ${safe(order.customer_name)}`, 60, y);
  y -= 18;
  draw(`Email: ${safe(order.customer_email)}`, 60, y);
  y -= 18;
  draw(`Telefon: ${safe(order.customer_phone)}`, 60, y);

  // 📦 Specifikacije
  section("SPECIFIKACIJE");
  const specs = [
    ["Kategorija", order.category],
    ["Model", order.model],
    ["Čistoća", order.purity],
    ["Boja", order.color],
    ["Količina", order.quantity],
    ["Status", order.status],
  ];
  specs.forEach(([label, val]) => {
    draw(`${label}: ${safe(val)}`, 60, y);
    y -= 18;
  });

  // 💍 Detalji
  section("DETALJI");
  const details = [
    ["Veličina (muška)", order.male_size],
    ["Veličina (ženska)", order.female_size],
    ["Kamenje", order.stones],
    ["Gravura 1", order.engraving_1],
    ["Gravura 2", order.engraving_2],
    ["Zajednička gravura", order.joint_engraving],
  ];
  details.forEach(([label, val]) => {
    draw(`${label}: ${safe(val)}`, 60, y);
    y -= 18;
  });

  // 💬 Komentar
  section("DODATNE NAPOMENE");
  draw(safe(order.additional_comment), 60, y);
  y -= 40;

  // 🖼️ Skica
  if (order.sketch_url) {
    section("SKICA");
    try {
      const imgBuffer = await fetch(order.sketch_url).then((r) => r.arrayBuffer());
      const img = await pdfDoc.embedPng(imgBuffer);
      page.drawImage(img, { x: 60, y: y - 180, width: 160, height: 160 });
      y -= 200;
    } catch {
      draw("⚠️ Skica nije učitana", 60, y);
      y -= 18;
    }
  }

  // 🧩 QR kod
  try {
    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&margin=0&data=${encodeURIComponent(
      order.order_no
    )}`;
    const buf = await fetch(qrUrl).then((r) => r.arrayBuffer());
    const img = await pdfDoc.embedPng(buf);
    page.drawImage(img, { x: width - 130, y: 60, width: 90, height: 90 });
    draw("QR → digitalni nalog", width - 160, 50, 8);
  } catch {}

  draw(`Generated by ORCAFX · ${new Date().toLocaleString("hr-HR")}`, 40, 40, 9);

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes).toString("base64");
}

// 📧 Mail sender
async function sendEmail(to, pdfBase64, order_no) {
  const payload = {
    sender: { name: "Zlatarna Krizek", email: "noreply@krizek.hr" },
    to: [{ email: to }],
    subject: `Radni nalog ${order_no}`,
    htmlContent: `<p>Poštovani,</p><p>U privitku se nalazi radni nalog <b>${order_no}</b>.</p><p>Lijep pozdrav,<br>Zlatarna Križek</p>`,
    attachment: [{ name: `${order_no}.pdf`, base64Content: pdfBase64 }],
  };
  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: { accept: "application/json", "content-type": "application/json", "api-key": BREVO_API_KEY },
    body: JSON.stringify(payload),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Brevo error: ${text}`);
  return JSON.parse(text);
}

// 🚀 Handler
module.exports = async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { workOrderId, emailToSend } = req.body || {};
  if (!workOrderId || !emailToSend)
    return res.status(400).json({ ok: false, error: "Missing parameters: workOrderId, emailToSend" });

  try {
    // Work order
    const { data: wo, error: woErr } = await supabase
      .from("work_orders")
      .select("*")
      .eq("id", workOrderId)
      .single();
    if (woErr || !wo) throw new Error("Work order not found");

    // Custom order merge
    let co = {};
    if (wo.custom_order_id) {
      const { data: coData } = await supabase.from("custom_orders").select("*").eq("id", wo.custom_order_id).single();
      if (coData) co = coData;
    }

    const order = { ...co, ...wo }; // 🔥 prefer custom_order podaci

    // Company info
    const { data: company } = await supabase
      .from("company_profile")
      .select("legal_name,address_line,city,country,email,phone,tax_id")
      .limit(1)
      .single();

    // PDF
    const pdfBase64 = await buildPdf(order, company);

    if (emailToSend === "printonly@local")
      return res.status(200).json({ ok: true, pdfBase64, order_no: order.order_no });

    // Mail
    const result = await sendEmail(emailToSend, pdfBase64, order.order_no);

    await supabase.rpc("fn_wo_log_email", {
      p_work_order_id: workOrderId,
      p_to: emailToSend,
      p_status: "SENT",
      p_provider_id: result?.messageId ?? null,
      p_error: null,
      p_payload: result ?? {},
    });

    return res.status(200).json({ ok: true, result });
  } catch (e) {
    console.error("❌ send.js error:", e.message);
    return res.status(500).json({ ok: false, error: e.message });
  }
};
