// api/workorders/send.js
import fs from "fs";
import path from "path";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { createClient } from "@supabase/supabase-js";

// 🔑 ENVIRONMENT VARIABLES
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const BREVO_API_KEY = process.env.BREVO_API_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// 📄 FONT PATH
const FONT_PATH = path.join(process.cwd(), "public", "fonts", "NotoSans-Regular.ttf");

// ---------- PDF BUILDER ----------
async function buildPdf(order, company) {
  const pdfDoc = await PDFDocument.create();
  pdfDoc.registerFontkit(fontkit);

  let fontBytes;
  try {
    fontBytes = fs.readFileSync(FONT_PATH);
  } catch (e) {
    console.warn("⚠️ Font not found, using Helvetica fallback:", e.message);
  }

  const font = fontBytes
    ? await pdfDoc.embedFont(fontBytes)
    : await pdfDoc.embedFont(StandardFonts.Helvetica);

  const page = pdfDoc.addPage([595, 842]);
  const { width, height } = page.getSize();

  const draw = (text, x, y, size = 11) =>
    page.drawText(String(text ?? "-"), { x, y, size, font, color: rgb(0, 0, 0) });

  // 🏢 HEADER — COMPANY INFO
  const companyName = company?.legal_name || "Zlatarna Krizek doo";
  const address = [company?.address_line, company?.city, company?.country]
    .filter(Boolean)
    .join(", ");
  let y = height - 40;

  if (company?.logo_url) {
    try {
      const buf = await fetch(company.logo_url).then((r) => r.arrayBuffer());
      let img;
      try {
        img = await pdfDoc.embedPng(buf);
      } catch {
        img = await pdfDoc.embedJpg(buf);
      }
      page.drawImage(img, { x: 40, y: y - 32, width: 96, height: 32 });
    } catch (e) {
      console.warn("⚠️ Logo failed:", e.message);
    }
  }

  draw(companyName, 160, y, 16);
  draw(`${address} · ${company?.email || ""} · ${company?.phone || ""}`, 160, y - 18, 10);

  y -= 50;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 1, color: rgb(0.1, 0.1, 0.1) });
  y -= 24;

  // 🧾 TITLE
  draw(`RADNI NALOG — ${order.order_no ?? ""}`, 40, y, 18);
  y -= 24;
  draw(`Datum narudžbe: ${formatDate(order.order_date)}`, 40, y);
  draw(`Rok izrade: ${formatDate(order.due_date)}`, 300, y);
  y -= 22;

  // Helper section
  const section = (title) => {
    y -= 12;
    page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.5, color: rgb(0.5, 0.5, 0.5) });
    y -= 20;
    draw(title, 40, y, 13);
    y -= 18;
  };

  // 👤 CUSTOMER
  section("KUPAC");
  draw(`Ime: ${order.customer_name ?? "-"}`, 60, y);
  y -= 18;
  draw(`Email: ${order.customer_email ?? "-"}`, 60, y);
  y -= 18;
  draw(`Telefon: ${order.customer_phone ?? "-"}`, 60, y);
  y -= 8;

  // 📦 SPECIFIKACIJE
  section("SPECIFIKACIJE");
  const specs = [
    ["Kategorija", order.category],
    ["Model", order.model],
    ["Čistoća", order.purity],
    ["Boja", order.color],
    ["Količina", order.quantity],
    ["Status", order.status],
  ];
  for (const [k, v] of specs) {
    draw(`${k}: ${v ?? "-"}`, 60, y);
    y -= 18;
  }
  y -= 6;

  // 💍 DETALJI
  section("DETALJI");
  const details = [
    ["Veličina (muška)", order.male_size],
    ["Veličina (ženska)", order.female_size],
    ["Kamenje", order.stones],
    ["Gravura 1", order.engraving_1],
    ["Gravura 2", order.engraving_2],
    ["Zajednička gravura", order.joint_engraving],
  ];
  for (const [k, v] of details) {
    draw(`${k}: ${v ?? "-"}`, 60, y);
    y -= 18;
  }
  y -= 6;

  // 💬 KOMENTAR
  section("DODATNO");
  multiLine(page, font, order.additional_comment ?? "-", 60, y, 11, 460, 16);
  y -= 90;

  // 🖼️ SKICA
  if (order.sketch_url) {
    section("SKICA");
    try {
      const buf = await fetch(order.sketch_url).then((r) => r.arrayBuffer());
      let img;
      try {
        img = await pdfDoc.embedPng(buf);
      } catch {
        img = await pdfDoc.embedJpg(buf);
      }
      const W = 180,
        H = 180;
      page.drawImage(img, { x: 60, y: y - H, width: W, height: H });
      y -= H + 10;
    } catch (e) {
      draw("⚠️ Skica nije učitana", 60, y);
      y -= 18;
    }
  }

  // FOOTER
  y -= 10;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.5, color: rgb(0.6, 0.6, 0.6) });
  y -= 12;
  draw(
    `Generated by ORCAFX · ${companyName} · ${new Date().toLocaleString("hr-HR")}`,
    40,
    y,
    9
  );

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes).toString("base64");
}

// ---------- UTILS ----------
function formatDate(v) {
  if (!v) return "-";
  try {
    return new Date(v).toLocaleString("hr-HR");
  } catch {
    return String(v);
  }
}
function multiLine(page, font, text, x, y, size, maxWidth, leading) {
  const words = String(text || "-").split(/\s+/);
  let line = "";
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    const width = font.widthOfTextAtSize(test, size);
    if (width > maxWidth) {
      page.drawText(line, { x, y, size, font });
      y -= leading;
      line = w;
    } else {
      line = test;
    }
  }
  if (line) page.drawText(line, { x, y, size, font });
}

// ---------- SEND EMAIL ----------
async function sendEmail(to, pdfBase64, order_no) {
  const payload = {
    sender: { name: "Zlatarna Krizek", email: "noreply@krizek.hr" },
    to: [{ email: to }],
    subject: `Radni nalog ${order_no}`,
    htmlContent: `<p>Poštovani,</p><p>U privitku se nalazi radni nalog <b>${order_no}</b>.</p><p>Lijep pozdrav,<br>Zlatarna Krizek</p>`,
    attachment: [{ name: `${order_no}.pdf`, base64Content: pdfBase64 }],
  };
  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: {
      accept: "application/json",
      "content-type": "application/json",
      "api-key": BREVO_API_KEY,
    },
    body: JSON.stringify(payload),
  });
  const txt = await res.text();
  if (!res.ok) throw new Error(`Brevo error: ${txt}`);
  return JSON.parse(txt);
}

// ---------- HANDLER ----------
export default async function handler(req, res) {
  if (req.method !== "POST")
    return res.status(405).json({ error: "Method not allowed" });

  const { workOrderId, emailToSend } = req.body || {};
  if (!workOrderId || !emailToSend) {
    return res
      .status(400)
      .json({ ok: false, error: "Missing parameters: workOrderId, emailToSend" });
  }

  try {
    // 1️⃣ Work order
    const { data: order, error: woErr } = await supabase
      .from("work_orders")
      .select("*")
      .eq("id", workOrderId)
      .single();
    if (woErr || !order) throw new Error("Work order not found");

    // 2️⃣ Company info
    const { data: company, error: cErr } = await supabase
      .from("company_profile")
      .select("legal_name, address_line, city, country, email, phone, logo_url")
      .limit(1)
      .single();
    if (cErr) console.warn("⚠️ company_profile fetch:", cErr.message);

    // 3️⃣ Generate PDF
    const pdfBase64 = await buildPdf(order, company);

    // 4️⃣ Print only
    if (emailToSend === "printonly@local") {
      return res.status(200).json({ ok: true, pdfBase64, order_no: order.order_no });
    }

    // 5️⃣ Send email
    const result = await sendEmail(emailToSend, pdfBase64, order.order_no);

    // 6️⃣ Log success
    await supabase.rpc("fn_wo_log_email", {
      p_work_order_id: workOrderId,
      p_to: emailToSend,
      p_status: "SENT",
      p_provider_id: result?.messageId ?? null,
      p_error: null,
      p_payload: result ?? {},
    });

    return res.status(200).json({ ok: true, result });
  } catch (e) {
    console.error("❌ send.js error:", e.message);

    try {
      await supabase.rpc("fn_wo_log_email", {
        p_work_order_id: req.body?.workOrderId ?? null,
        p_to: req.body?.emailToSend ?? null,
        p_status: "FAILED",
        p_provider_id: null,
        p_error: e.message?.slice(0, 300) || "unknown",
        p_payload: {},
      });
    } catch (err2) {
      console.warn("⚠️ Logging fail:", err2.message);
    }

    return res.status(500).json({ ok: false, error: e.message });
  }
}
